### ISSUE TITLE
Docs for new logstash-filter-elastic_integration plugin are not being picked up for LSR

### ISSUE THREAD

**Issue by karenzone** [elastic/docs-tools#105]
Related: https://github.com/elastic/logstash-docs/pull/1598

We recently added support for plugins outside of the `logstash-plugins` GitHub org with #103. 

###  [Versioned Plugin Reference (VPR)](https://www.elastic.co/guide/en/logstash-versioned-plugins/current/index.html) 
* The VPR build is picking up changes as expected.   ✅ 
  Example: [auto generated update](https://github.com/elastic/logstash-docs/pull/1597/files) picked up `filter-elastic_integration v0.1.4`  

### [Logstash Reference (LSR)](https://www.elastic.co/guide/en/logstash/master/index.html)
* The filter-elastic_integration content that is currently published was added manually (PR [#1579](https://github.com/elastic/logstash-docs/pull/1579)) with the plan to have it update programmatically for future version bumps.
* The plugin has been added to `rakelib/plugins-metadata.json` (PR [#15692](https://github.com/elastic/logstash/pull/15692))
* I generated [plugin docs for `main`](https://github.com/elastic/logstash-docs/pull/1598) after `filter-elastic_integration v9.1.4` came through for the VPR.  
  The v9.1.4 update didn't get picked up for the LSR.  ❌ 

### Published pages
* Link to VPR page: https://www.elastic.co/guide/en/logstash-versioned-plugins/current/v0.1.4-plugins-filters-elastic_integration.html
* Link to LSR page: https://www.elastic.co/guide/en/logstash/master/plugins-filters-elastic_integration.html
<img width="1870" alt="Screen Shot 2024-01-25 at 5 51 38 PM" src="https://github.com/elastic/docs-tools/assets/35154725/e69a7900-f4d9-48e3-b2ac-35edde6f770e">

@mashhurs, thanks again for your great work on the docs tooling. It seems that we have one more kink to work out before this works seamlessly.

**Comment by mashhurs** [comment]
Hm, interesting. `./gradlew generatePluginsVersion` somehow didn't include `elastic_integration` plugin in `plugins_version_docs.json`. I will investigate and fix this, assigning myself.

**Comment by karenzone** [comment]
#### Updated

Let's work with @roaksoax to get this work into a sprint.


<img width="1722" alt="Screen Shot 2024-03-05 at 6 20 46 PM" src="https://github.com/elastic/docs-tools/assets/35154725/fcd9201f-7eb7-404f-88d1-f96c6e3e642f">

**Comment by mashhurs** [comment]
@karenzone this was covered when non-OSS feature was introduced. Sorry that I forgot to update here 🤦 
I have just run the workflow to double check and it is here: I have https://github.com/elastic/logstash-docs/pull/1613/files#diff-d795e5afb754865b186622bfd833c211c013d0a49f7b8d050e06915dab87ffa3

**Comment by karenzone** [comment]
Awesome! Thanks for fixing this. 
Do you have a PR number we can link to this issue for future reference?  

I'm going to delete my previous comment to avoid confusion. :-)

**Comment by mashhurs** [comment]
> Awesome! Thanks for fixing this. Do you have a PR number we can link to this issue for future reference?
> 
> I'm going to delete my previous comment to avoid confusion. :-)

Here it is: https://github.com/elastic/logstash/pull/15769

**Comment by karenzone** [comment]
Fixed with merge of https://github.com/elastic/logstash/pull/15769

**Comment by karenzone** [comment]
Fixed with merge of https://github.com/elastic/logstash/pull/15769
