### ISSUE TITLE
New snmp-integration docs not being picked up for Logstash Reference (LSR)

### ISSUE THREAD

**Issue by karenzone** [elastic/docs-tools#106]
Integration-snmp docs are not being picked up in LSR docgen.  

### Some context
* New [integration-snmp](https://github.com/logstash-plugins/logstash-integration-snmp) plugin was added to rakelib/plugins-metadata.json:  https://github.com/elastic/logstash/pull/16137 on 2024-05-17, Friday. 
* Integration-snmp was [bumped to v4.0.2](https://github.com/logstash-plugins/logstash-integration-snmp/pull/61) and published on 2024-05-20, Monday, and was picked up for the Versioned Plugin Reference (VPR).  
* @karenzone kicked off a [LSR docgen job](https://github.com/elastic/logstash-docs/actions/workflows/reference_docs.yml). The job completed successfully, but it didn't pick up any changes. 
   <img width="753" alt="Screen Shot 2024-05-20 at 5 00 41 PM" src="https://github.com/elastic/docs-tools/assets/35154725/068a450d-e382-4218-8f09-b8313984113b"> 
* This message in the output indicates that `integration-snmp` is getting skipped because it is tagged as `non-default` integration.  (You can see the same messaging for `integration-zeromq`, which we DO NOT want getting picked up at this time. 
   <img width="952" alt="Screen Shot 2024-05-20 at 5 04 25 PM" src="https://github.com/elastic/docs-tools/assets/35154725/68ee26fa-6e10-4ae5-8ec5-2f86a884133c">
* We regularly publish non-default input, output, filter, and codec plugins, but the tooling treats integrations differently (https://github.com/elastic/docs-tools/blob/main/plugindocs.rb#L66-L69): 
   <img width="863" alt="Screen Shot 2024-05-20 at 5 12 35 PM" src="https://github.com/elastic/docs-tools/assets/35154725/a75a7d7c-a2e0-495b-99bb-83b0fe5b3c30">

### How do we want to handle this?
* It appears that we have two other non-default integration plugins. 
   <img width="753" alt="Screen Shot 2024-05-20 at 5 15 40 PM" src="https://github.com/elastic/docs-tools/assets/35154725/3fc4b13c-23e0-484b-8aaa-1b7500bff9a3">
  * It seems weird that the other two non-default plugins are being picked up for the docgen job, but they aren't mentioned in the [skiplist](https://github.com/elastic/logstash/blob/main/rakelib/plugins-metadata.json). So obviously, there's some way to get plugins building that I'm not aware of.  Can we figure out what that is, and then perhaps add those two in-process plugins to the skiplist with `default-plugins: false` and `"skip-list": true`?  And then change docs tooling to allow non-default integration plugins such as `integration-snmp` is in the interim?

**Comment by karenzone** [comment]
Another possible solution:  Could we add those to [_this_ skiplist](https://github.com/elastic/docs-tools/blob/main/settings.yml) to skip the whole repo?

**Comment by jsvd** [comment]
> Another possible solution: Could we add those to [this skiplist](https://github.com/elastic/docs-tools/blob/main/settings.yml) to skip the whole repo?

Indeed, the [skip list](https://github.com/elastic/docs-tools/blob/main/settings.yml) in docs-tools should be only for repos that aren't plugins, so keeping:

```yaml
skip:
  - logstash-core-plugin-api
  - logstash-patterns-core
  - logstash-devutils
```
is fine, and the rest should be moved to [plugins-metadata.json](https://github.com/elastic/logstash/blob/main/rakelib/plugins-metadata.json), and we should be able to remove the condition to automatically exclude non default integrations, and exclude them if they have "skip-list":true  https://github.com/elastic/docs-tools/blob/main/plugindocs.rb#L66-L69

**Comment by karenzone** [comment]
PRs:
- https://github.com/elastic/logstash/pull/16174
- https://github.com/elastic/docs-tools/pull/107

**Comment by karenzone** [comment]
UPDATE:  The root cause still exists, but this particular issue was resolved when `integration-snmp` became a default plugin with the merge of https://github.com/elastic/logstash/pull/16180.
