### ISSUE TITLE
Docs build failures

### ISSUE THREAD

**Issue by jordansissel** [elastic/docs-tools#2]
Missing xmllint:

* https://logstash-ci.elastic.co/job/elastic+docs-tools+master+sync-logstash-5.x-docs/14/console
* https://logstash-ci.elastic.co/job/elastic+docs-tools+master+sync-logstash-5.x-docs/19/console
* https://logstash-ci.elastic.co/job/elastic+docs-tools+master+sync-logstash-5.x-docs/18/console
* https://logstash-ci.elastic.co/job/elastic+docs-tools+master+sync-logstash-master-docs/65/console
...

Missing Digest::MD5:

* https://logstash-ci.elastic.co/job/elastic+docs-tools+master+sync-logstash-5.x-docs/16/console

`Can't locate parent.pm in @INC`

* https://logstash-ci.elastic.co/job/elastic+docs-tools+master+sync-logstash-5.1-docs/42/console
* https://logstash-ci.elastic.co/job/elastic+docs-tools+master+sync-logstash-5.1-docs/53/console

Unknown (probably a corrupt/incomplete git clone)

* https://logstash-ci.elastic.co/job/elastic+docs-tools+master+sync-logstash-5.x-docs/17/console
* https://logstash-ci.elastic.co/job/elastic+docs-tools+master+sync-logstash-5.x-docs/16/console

**Comment by jordansissel** [comment]
@elasticdog Any ideas? Lots of different failures from the weekend and some of them look like missing dependencies on Jenkins workers?

**Comment by elasticdog** [comment]
Interesting, I thought xmllint was pulled in the the libxstl/libxml stuff that I pushed out, but can investigate. I went ahead and cleared out the docs-tools workspaces on those two nodes, so hopefully the corrupt checkout issue will be gone(ish). I'll also take a look at the other failures, but it might take a bit as I'm conferencing this week.

**Comment by elasticdog** [comment]
Quick update, I'm installing the `perl-parent` package on RedHat based slave nodes at the moment, which should fix up that particular error (I don't think it applies on the Ubuntu hosts, as far as I've seen). The missing `xmllint` I've not tracked down quite yet.

**Comment by elasticdog** [comment]
I think we've been able to capture and automate the various missing dependencies across the distros at this point. I'll leave this issue open for a couple more days to watch the jobs for any dependency-related failures, but I think things should be in much better shape now.

**Comment by elasticdog** [comment]
Okay, I think things are looking better. We've had a couple of failures due to memory contention on one particular slave node, but that has been an ongoing issue with the Docker hosts not freeing up resources. I've bounced that box and will continue the Docker-related discussion with the infra team. Resolving for now, but please let me know if you see any other dependency-related failures.

**Comment by jordansissel** [comment]
Confirmed! Thank you for making this more stable :)
