### ISSUE TITLE
Create logstash-plugins docbook tooling

### ISSUE THREAD

**Issue by jordansissel** [elastic/docs-tools#4]
As discussed today with @dedemorton and @ph, we're going to try getting logstash plugins documentation centered in a new docbook.

The rough plan is:

* For every plugin in logstash-plugins
* and for every minor version
* put asciidoc in the right place in this docbook, roughly: /plugin-name/x.y/...

**Comment by dedemorton** [comment]
I've described a proposed doc structure for the new plugin book here: https://github.com/elastic/logstash/issues/6683

**Comment by dedemorton** [comment]
I think we can close this issue now. yay! (I don't have access to close issues in this repo)
