### ISSUE TITLE
Restrict docgen builds to machines equipped with the right set up

### ISSUE THREAD

**Issue by karenzone** [elastic/docs-tools#44]
When we kick off a [jenkins docgen](https://logstash-ci.elastic.co/view/Docs/job/elastic+docs-tools+logstash-plugin-docs/) job, there's no guarantee that the machine that gets the job is properly equipped. 

Sample of recent failures:
* https://logstash-ci.elastic.co/view/Docs/job/elastic+docs-tools+logstash-plugin-docs/122/console on `logstash-ci-immutable-ubuntu-2004-lts-1594685912225329042`
```
+ cd ../logstash
+ ../docs/build_docs --asciidoctor --respect_edit_url_overrides --doc docs/index.asciidoc --resource=../logstash-docs/docs/ --chunk 1
/usr/bin/env: ‘python’: No such file or directory
```

* https://logstash-ci.elastic.co/view/Docs/job/elastic+docs-tools+logstash-plugin-docs/124/console on `on logstash-ci-immutable-debian-8-1594762967005309446`

```
+ cd ../logstash
+ ../docs/build_docs --asciidoctor --respect_edit_url_overrides --doc docs/index.asciidoc --resource=../logstash-docs/docs/ --chunk 1
ERROR:docker build:buildkit not supported by daemon
Command '['docker', 'image', 'build', '--target', 'build', '--tag', 'docker.elastic.co/docs/build:latest', '/var/lib/jenkins/workspace/elastic+docs-tools+logstash-plugin-docs/docs']' returned non-zero exit status 1
```

Workaround:
* Kick off another build and hope for a different machine assignment.

**Comment by karenzone** [comment]
For our company-wide docs build, I just noticed a message while a docs build was queueing up: "No machines matching the `docs` label are available."  So maybe there's a way to tag machines that are adequately equipped with a `docs` label???

**Comment by karenzone** [comment]
@gtback Thanks for working on this

**Comment by gtback** [comment]
@karenzone the change should be deployed. I think those jobs run on-demand (based on the file they're configured in), so if you wanted to give it a try or two, make sure they're running on an Ubuntu 18.04 worker, then I think this issue is good to close.

**Comment by karenzone** [comment]
Thanks for the magic, @gtback!
