### ISSUE TITLE
VPR: Allow adding a non-standard landing page (manually or programmatically) 

### ISSUE THREAD

**Issue by karenzone** [elastic/docs-tools#53]
Our docs tooling handles new and updated plugin docs on a scale that wouldn't be feasible (or even possible) manually. When we add new exceptions to the normal flow, we have to make changes to docs tooling or figure out workarounds. 

In early 2021, we added the concept of an aliased plugin (elastic_agent-> beats) to allow for plugins in transition to use a shared repo/code base. This solution will likely be temporary, but we need to be able to support it in the interim. 

Even beyond aliasing, this capability could prove useful as we come up with new exceptions and use cases. 

Immediate need: https://github.com/elastic/logstash-docs/pull/1011. We can't add input-elastic_agent to the Logstash Reference until we have a landing page in the Versioned Plugin Reference (VPR). 
Possible workaround: We could create and use a non-standard plugin header for the aliases that doesn't require a landing page in the VPR. That solution would be less than ideal because it would be a fair amount of work for a less-than-ideal user experience. 

Unplanned test case:
* I added an input-elastic_agent landing page and an include statement to the list of input plugins: https://github.com/elastic/logstash-docs/pull/1021
* It was overwritten by an automated update: https://github.com/elastic/logstash-docs/commit/1ebe826daaea1a933b153db5ecbc6818fb6a07c0

**Comment by karenzone** [comment]
Notes from @jsvd:  
> We may need to hard code this alias in one more place and make the generator script pre-fill the index with any aliases

**Comment by andsel** [comment]
@yaauie about the retrieval of the alias yml file, we could simply grab that file from github, without cloning the Logstash repo.

About the second concern when the `plugin_indexes` is populated https://github.com/elastic/docs-tools/blob/95137ffcec5af8e469db2246dce3f100594ed576/versioned_plugins.rb#L175 we could force the aliases to have a special version, for example `0.0.0`

**Comment by karenzone** [comment]
I'm not disagreeing with any proposals so far.  Just adding a user requirement. 

I need the ability to add a landing page that points to the landing page for the target alias (meaning the landing page I need won't have any linked versioned docs of its own). 

The simpler we can make this the better. Every time we add more specialized processing, we add overhead to the system and put up new hoops we need to jump through the next time we encounter an exception flow (like when we added java core plugins, integrations, listed plugins, and now aliases).  As the primary user, I need as much flexibility as possible without having to design new workarounds.  And, we don't yet know how conversion to the all new docs system will affect all of this.
