### ISSUE TITLE
Unexpected value for default_plugin setting

### ISSUE THREAD

**Issue by karenzone** [elastic/docs-tools#56]
We recently added a new integration for enterprise_search[(1)](https://github.com/logstash-plugins/logstash-integration-elastic_enterprise_search/pull/1) and followed up with changes[(2)](https://github.com/elastic/logstash/pull/12925) to the [metadata.json file](https://github.com/elastic/logstash/blob/master/rakelib/plugins-metadata.json) to get docs generating properly. The PR added the integration to the json file, and removed the stand-alone output-elastic_app_search.

When we tested the PR by manually generating docs[(3)]( https://github.com/elastic/logstash-docs/pull/1032), we noticed that the default_plugin setting for output-elastic_app_search was changed and incorrect. (It should have been `1`, but was changed to `0`.  

We reproduced this behavior when we used the on-demand job to generate plugin docs[(4)](https://github.com/elastic/logstash-docs/pull/1033).

**NEXT STEPS:** 
* Figure out what's going on
* Fix it
* Update internal documentation as appropriate 

(1) https://github.com/logstash-plugins/logstash-integration-elastic_enterprise_search/pull/1
(2) https://github.com/elastic/logstash/pull/12925
(3) https://github.com/elastic/logstash-docs/pull/1032
(4) https://github.com/elastic/logstash-docs/pull/1033

**Comment by karenzone** [comment]
Still a problem: https://github.com/elastic/logstash-docs/pull/1065

**Comment by kares** [comment]
with the recent [master generation](https://github.com/elastic/logstash-docs/pull/1096) seems this is no longer an issue?
(the issue resolved with a fix for https://github.com/elastic/docs-tools/issues/57)

**Comment by karenzone** [comment]
Yes. Thanks for the fix! ❤️
